global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']

  - job_name: 'nginx'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:9113']  # Nginx exporter if installed

  - job_name: 'minecraft'
    static_configs:
      - targets: ['minecraft-exporter:9150']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

